In [2]:
import numpy as np

# OR

In [3]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=[0,1,1,1]

In [5]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y




epoch  0
[1 1 1 1] [0, 1, 1, 1]
epoch  1
[1 0 1 1] [0, 1, 1, 1]
epoch  2
[1 1 1 1] [0, 1, 1, 1]
epoch  3
[0 0 1 1] [0, 1, 1, 1]
epoch  4
[1 1 1 1] [0, 1, 1, 1]
epoch  5
[0 1 1 1] [0, 1, 1, 1]


In [6]:
inputs=[[1,0]]

predict(inputs)[0]

1

# NOT

In [8]:
x=np.array([0,1])
y=[1,0]

In [9]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y


epoch  0
[1 1] [1, 0]
epoch  1
[1 1] [1, 0]
epoch  2
[0 0] [1, 0]
epoch  3
[1 1] [1, 0]
epoch  4
[0 0] [1, 0]
epoch  5
[1 0] [1, 0]


In [13]:
inputs=[[0]]

predict(inputs)[0][0]

1

# AND

In [14]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=[0,0,0,1]

In [15]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y

epoch  0
[1 0 1 1] [0, 0, 0, 1]
epoch  1
[0 0 1 0] [0, 0, 0, 1]
epoch  2
[0 0 1 1] [0, 0, 0, 1]
epoch  3
[0 0 1 0] [0, 0, 0, 1]
epoch  4
[0 0 1 0] [0, 0, 0, 1]
epoch  5
[0 0 1 1] [0, 0, 0, 1]
epoch  6
[0 0 0 0] [0, 0, 0, 1]
epoch  7
[0 0 1 1] [0, 0, 0, 1]
epoch  8
[0 0 0 0] [0, 0, 0, 1]
epoch  9
[0 1 1 1] [0, 0, 0, 1]
epoch  10
[0 0 0 0] [0, 0, 0, 1]
epoch  11
[0 0 0 1] [0, 0, 0, 1]


In [16]:
inputs=[[1,0]]

predict(inputs)[0]

0

# NAND

In [17]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=[1,1,1,0]

In [18]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y

epoch  0
[1 1 1 1] [1, 1, 1, 0]
epoch  1
[1 1 1 1] [1, 1, 1, 0]
epoch  2
[0 1 1 1] [1, 1, 1, 0]
epoch  3
[0 1 1 1] [1, 1, 1, 0]
epoch  4
[0 0 0 0] [1, 1, 1, 0]
epoch  5
[1 1 1 1] [1, 1, 1, 0]
epoch  6
[1 1 1 1] [1, 1, 1, 0]
epoch  7
[1 0 0 0] [1, 1, 1, 0]
epoch  8
[1 1 1 1] [1, 1, 1, 0]
epoch  9
[1 1 1 0] [1, 1, 1, 0]


In [19]:
inputs=[[1,0]]

predict(inputs)[0]

1

# NOR

In [22]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=[0,0,0,1]

In [23]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y

epoch  0
[1 1 1 1] [0, 0, 0, 1]
epoch  1
[0 0 1 1] [0, 0, 0, 1]
epoch  2
[0 0 0 1] [0, 0, 0, 1]


In [24]:
inputs=[[1,0]]

predict(inputs)[0]

0

# Tautology

In [25]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=[1,1,1,1]

In [26]:
def act(x):
    return (x>=0).astype(int)
def training(x,y,epoch,learning_rate):
    try:
        feature=x.shape[1]
    except:
        feature=1
    if feature!=1:
        w=np.random.normal((feature,1))
    else:
        w=np.random.normal((feature))
    b=0.5
    for n in range(epoch):
        yc=np.dot(x,w)+b
        print('epoch ',n)
        wsum=act(yc)
        print(wsum,y)
        error=y-wsum
        w+=np.dot(error,x)*learning_rate
        b+=np.sum(error)*learning_rate
        if all(error==0):
            return w,b
w,b=(training(x,y,100,0.5))
def predict(inputs):
    inputs=np.array(inputs)
    y=np.dot(inputs,w)+b
    y=act(y)
    return y

epoch  0
[1 1 1 1] [1, 1, 1, 1]


In [27]:
inputs=[[1,0]]

predict(inputs)[0]

1